workflows:
  ios:
    name: Build iOS App
    max_build_duration: 60
    scripts:
      - name: Install dependencies
        script: |
          cd slpodmobile/Flutter  # ไปที่โฟลเดอร์ Flutter ภายใน slpodmobile
          flutter doctor
          flutter pub get
      - name: Build iOS
        script: |
          cd slpodmobile/Flutter  # ไปที่โฟลเดอร์ Flutter อีกครั้ง
          flutter build ios --release
    artifacts:
      - build/ios/ipa/*.ipa



