workflows:
  ios:
    name: Build iOS App
    max_build_duration: 60
    scripts:
      - name: Install dependencies
        script: |
          cd slpodmobile # ไปที่โฟลเดอร์โปรเจกต์ Flutter
          flutter doctor  # ตรวจสอบการตั้งค่าของ Flutter
          flutter pub get  # ดึง dependencies ที่จำเป็น
      - name: Build iOS
        script: |
          cd slpodmobile # ไปที่โฟลเดอร์โปรเจกต์
          flutter build ios --release # สร้างแอป iOS ในโหมด Release
    artifacts:
      - build/ios/ipa/*.ipa # กำหนดให้บันทึกไฟล์ .ipa ที่สร้างขึ้น



